### ISSUE TITLE
Botched linebreaks in legacy reviews

### ISSUE THREAD

**Issue by rr-** [rr-/TRCustoms#220]

**Comment by rr-** [comment]
Fixed on staging, LMK if it's good. The script doesn't touch any of the reviews made / updated after scraping.

**Comment by Klona13** [comment]
That's right. The script fixes all scraped reviews.
The new/edited reviews not fixed.
